version: '3'
services:
    mongodb:
        image: mongo:4.0.8
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: imlong
            MONGO_INITDB_ROOT_PASSWORD: 123456
            MONGO_INITDB_DATABASE: vnexpress
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        ports:
            - 27017:27017
        volumes:
            - mongodbdata:/data/db
        networks:
            - appnetworks

    server:
        build:
            context: Vnexpress
            dockerfile: Dockerfile
        container_name: server
        image: digitalocean.com/flask-python:3.6
        restart: unless-stopped
        environment:
            APP_ENV: "prod"
            APP_DEBUG: "False"
            APP_PORT: 5000
            SUB_URL: 
            MONGODB_DATABASE: vnexpress
            MONGODB_USERNAME: imlong
            MONGODB_PASSWORD: 123456
            MONGODB_HOSTNAME: mongodb
        ports:
            - "5000:5000"
        volumes:
            - serverdata:/var/www
        depends_on:
            - mongodb
        networks:
            - appnetworks

    client:
        build:
            context: Front-End
        container_name: client
        command: ["npm", "start"]
        volumes:
            - clientdata/:/app
            - /app/node_modules
        networks:
            - appnetworks
        depends_on:
            - server
        ports:
            - "3000:3000"
        stdin_open: true


    webserver:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: digitalocean.com/webserver:latest
        container_name: webserver
        restart: unless-stopped
        environment:
            APP_ENV: "prod"
            APP_NAME: "webserver"
            APP_DEBUG: "true"
            SERVICE_NAME: "webserver"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nginxdata:/var/log/nginx
        depends_on:
            - server
            - client
        networks:
            - appnetworks


networks:
    appnetworks:
        driver: bridge

volumes:
    mongodbdata:
        driver: local
    serverdata:
        driver: local
    clientdata:
        driver: local
    nginxdata:
        driver: local
