version: '3'
services:
    server:
        build:
            context: Vnexpress
            dockerfile: Dockerfile
        container_name: server
        image: digitalocean.com/flask-python:3.6
        restart: unless-stopped
        environment:
            APP_ENV: "prod"
            APP_DEBUG: "False"
            APP_PORT: 5000
            SUB_URL: 
            MONGODB_DATABASE: vnexpress
            MONGODB_USERNAME: twoman
            MONGODB_PASSWORD: twoman123456
            MONGODB_HOSTNAME: labando.com
        ports:
            - "5000:5000"
        volumes:
            - serverdata:/var/www
        networks:
            - appnetworks

    client:
        build:
            context: Front-End
        container_name: client
        command: ["npm", "run", "start:prod"]
        volumes:
            - clientdata/:/app
            - /app/node_modules
        networks:
            - appnetworks
        depends_on:
            - server
        ports:
            - "3000:3000"
        stdin_open: true


    webserver:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: digitalocean.com/webserver:latest
        container_name: webserver
        restart: unless-stopped
        environment:
            APP_ENV: "prod"
            APP_NAME: "webserver"
            APP_DEBUG: "true"
            SERVICE_NAME: "webserver"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nginxdata:/var/log/nginx
        depends_on:
            - server
            - client
        networks:
            - appnetworks


networks:
    appnetworks:
        driver: bridge

volumes:
    serverdata:
        driver: local
    clientdata:
        driver: local
    nginxdata:
        driver: local
